
source("tcc/scripts/src/Functions.R")
source("tcc/scripts/src/Imports.R")

year1.df <- readARFF(paste(dataframes.location[1], "1year.arff", sep = ""))
year2.df <- readARFF(paste(dataframes.location[1], "2year.arff", sep = ""))
year3.df <- readARFF(paste(dataframes.location[1], "3year.arff", sep = ""))
year4.df <- readARFF(paste(dataframes.location[1], "4year.arff", sep = ""))
year5.df <- readARFF(paste(dataframes.location[1], "5year.arff", sep = ""))

year1.noNA <- getCompleteCases(year1.df)
year2.noNA <- getCompleteCases(year2.df)
year3.noNA <- getCompleteCases(year3.df)
year4.noNA <- getCompleteCases(year4.df)
year5.noNA <- getCompleteCases(year5.df)

year1.complCasesPerc <- nrow(year1.noNA)/nrow(year1.df)
year2.complCasesPerc <- nrow(year2.noNA)/nrow(year2.df)
year3.complCasesPerc <- nrow(year3.noNA)/nrow(year3.df)
year4.complCasesPerc <- nrow(year4.noNA)/nrow(year4.df)
year5.complCasesPerc <- nrow(year5.noNA)/nrow(year5.df)

year1.class0Perc <- length(which(year1.noNA$class == "0"))/length(which(year1.df$class == "0"))
year1.class1Perc <- length(which(year1.noNA$class == "1"))/length(which(year1.df$class == "1"))
year2.class0Perc <- length(which(year2.noNA$class == "0"))/length(which(year2.df$class == "0"))
year2.class1Perc <- length(which(year2.noNA$class == "1"))/length(which(year2.df$class == "1"))
year3.class0Perc <- length(which(year3.noNA$class == "0"))/length(which(year3.df$class == "0"))
year3.class1Perc <- length(which(year3.noNA$class == "1"))/length(which(year3.df$class == "1"))
year4.class0Perc <- length(which(year4.noNA$class == "0"))/length(which(year4.df$class == "0"))
year4.class1Perc <- length(which(year4.noNA$class == "1"))/length(which(year4.df$class == "1"))
year5.class0Perc <- length(which(year5.noNA$class == "0"))/length(which(year5.df$class == "0"))
year5.class1Perc <- length(which(year5.noNA$class == "1"))/length(which(year5.df$class == "1"))
